--------------------------------------------------------
--  File created - quarta-feira-novembro-20-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CT_AMBIENTE
--------------------------------------------------------

  CREATE TABLE "RM552164"."CT_AMBIENTE" 
   (	"ID_AMBIENTE" NUMBER(19,0), 
	"DS_AMBIENTE" VARCHAR2(250 CHAR), 
	"NM_AMBIENTE" VARCHAR2(100 CHAR), 
	"DS_LABEL" VARCHAR2(100 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Table CT_CONSUMO_ENERGETICO
--------------------------------------------------------

  CREATE TABLE "RM552164"."CT_CONSUMO_ENERGETICO" 
   (	"ID_CONSUMO_ENERGETICO" NUMBER(19,0), 
	"VL_CONSUMO" NUMBER(10,2), 
	"DT_REGISTRO" TIMESTAMP (6), 
	"ID_DISPOSITIVO" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Table CT_DISPOSITIVO
--------------------------------------------------------

  CREATE TABLE "RM552164"."CT_DISPOSITIVO" 
   (	"ID_DISPOSITIVO" NUMBER(19,0), 
	"VL_CONSUMO_MEDIO" NUMBER(10,2), 
	"NM_DISPOSITIVO" VARCHAR2(150 CHAR), 
	"ST_DISPOSITIVO" VARCHAR2(15 CHAR), 
	"ID_AMBIENTE" NUMBER(19,0), 
	"ID_USUARIO" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Table CT_DISPOSITIVOS_USUARIO
--------------------------------------------------------

  CREATE TABLE "RM552164"."CT_DISPOSITIVOS_USUARIO" 
   (	"ID_DISPOSITIVO" NUMBER(19,0), 
	"ID_USUARIO" NUMBER(19,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Table CT_GENERO
--------------------------------------------------------

  CREATE TABLE "RM552164"."CT_GENERO" 
   (	"ID_GENERO" NUMBER(19,0), 
	"DS_GENERO" VARCHAR2(200 CHAR), 
	"NM_GENERO" VARCHAR2(30 CHAR), 
	"DS_LABEL" VARCHAR2(100 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Table CT_ROLE
--------------------------------------------------------

  CREATE TABLE "RM552164"."CT_ROLE" 
   (	"ID_ROLE" NUMBER(19,0), 
	"DS_LABEL" VARCHAR2(150 CHAR), 
	"NM_ROLE" VARCHAR2(25 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Table CT_ROLE_USUARIO
--------------------------------------------------------

  CREATE TABLE "RM552164"."CT_ROLE_USUARIO" 
   (	"ID_USUARIO" NUMBER(19,0), 
	"ID_ROLE" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Table CT_USUARIO
--------------------------------------------------------

  CREATE TABLE "RM552164"."CT_USUARIO" 
   (	"ID_USUARIO" NUMBER(19,0), 
	"DT_NASCIMENTO" DATE, 
	"DS_EMAIL" VARCHAR2(200 CHAR), 
	"NM_USUARIO" VARCHAR2(200 CHAR), 
	"DS_SENHA" VARCHAR2(255 CHAR), 
	"ID_GENERO" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Index SYS_C004001788
--------------------------------------------------------

  CREATE UNIQUE INDEX "RM552164"."SYS_C004001788" ON "RM552164"."CT_AMBIENTE" ("ID_AMBIENTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Index SYS_C004116734
--------------------------------------------------------

  CREATE UNIQUE INDEX "RM552164"."SYS_C004116734" ON "RM552164"."CT_CONSUMO_ENERGETICO" ("ID_CONSUMO_ENERGETICO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Index SYS_C004001801
--------------------------------------------------------

  CREATE UNIQUE INDEX "RM552164"."SYS_C004001801" ON "RM552164"."CT_DISPOSITIVO" ("ID_DISPOSITIVO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Index SYS_C004001807
--------------------------------------------------------

  CREATE UNIQUE INDEX "RM552164"."SYS_C004001807" ON "RM552164"."CT_GENERO" ("ID_GENERO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Index SYS_C004002658
--------------------------------------------------------

  CREATE UNIQUE INDEX "RM552164"."SYS_C004002658" ON "RM552164"."CT_ROLE" ("ID_ROLE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Index UK4N8PE124X2TXCMU68N8AS7OAO
--------------------------------------------------------

  CREATE UNIQUE INDEX "RM552164"."UK4N8PE124X2TXCMU68N8AS7OAO" ON "RM552164"."CT_ROLE" ("NM_ROLE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Index SYS_C004002661
--------------------------------------------------------

  CREATE UNIQUE INDEX "RM552164"."SYS_C004002661" ON "RM552164"."CT_ROLE_USUARIO" ("ID_USUARIO", "ID_ROLE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Index SYS_C004001814
--------------------------------------------------------

  CREATE UNIQUE INDEX "RM552164"."SYS_C004001814" ON "RM552164"."CT_USUARIO" ("ID_USUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  Constraints for Table CT_AMBIENTE
--------------------------------------------------------

  ALTER TABLE "RM552164"."CT_AMBIENTE" MODIFY ("ID_AMBIENTE" NOT NULL ENABLE);
  ALTER TABLE "RM552164"."CT_AMBIENTE" MODIFY ("DS_AMBIENTE" NOT NULL ENABLE);
  ALTER TABLE "RM552164"."CT_AMBIENTE" MODIFY ("NM_AMBIENTE" NOT NULL ENABLE);
  ALTER TABLE "RM552164"."CT_AMBIENTE" ADD PRIMARY KEY ("ID_AMBIENTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS"  ENABLE;
  ALTER TABLE "RM552164"."CT_AMBIENTE" MODIFY ("DS_LABEL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CT_CONSUMO_ENERGETICO
--------------------------------------------------------

  ALTER TABLE "RM552164"."CT_CONSUMO_ENERGETICO" MODIFY ("ID_CONSUMO_ENERGETICO" NOT NULL ENABLE);
  ALTER TABLE "RM552164"."CT_CONSUMO_ENERGETICO" MODIFY ("VL_CONSUMO" NOT NULL ENABLE);
  ALTER TABLE "RM552164"."CT_CONSUMO_ENERGETICO" MODIFY ("DT_REGISTRO" NOT NULL ENABLE);
  ALTER TABLE "RM552164"."CT_CONSUMO_ENERGETICO" MODIFY ("ID_DISPOSITIVO" NOT NULL ENABLE);
  ALTER TABLE "RM552164"."CT_CONSUMO_ENERGETICO" ADD PRIMARY KEY ("ID_CONSUMO_ENERGETICO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CT_DISPOSITIVO
--------------------------------------------------------

  ALTER TABLE "RM552164"."CT_DISPOSITIVO" MODIFY ("ID_DISPOSITIVO" NOT NULL ENABLE);
  ALTER TABLE "RM552164"."CT_DISPOSITIVO" MODIFY ("VL_CONSUMO_MEDIO" NOT NULL ENABLE);
  ALTER TABLE "RM552164"."CT_DISPOSITIVO" MODIFY ("NM_DISPOSITIVO" NOT NULL ENABLE);
  ALTER TABLE "RM552164"."CT_DISPOSITIVO" MODIFY ("ST_DISPOSITIVO" NOT NULL ENABLE);
  ALTER TABLE "RM552164"."CT_DISPOSITIVO" MODIFY ("ID_AMBIENTE" NOT NULL ENABLE);
  ALTER TABLE "RM552164"."CT_DISPOSITIVO" ADD PRIMARY KEY ("ID_DISPOSITIVO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS"  ENABLE;
  ALTER TABLE "RM552164"."CT_DISPOSITIVO" MODIFY ("ID_USUARIO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CT_DISPOSITIVOS_USUARIO
--------------------------------------------------------

  ALTER TABLE "RM552164"."CT_DISPOSITIVOS_USUARIO" MODIFY ("ID_DISPOSITIVO" NOT NULL ENABLE);
  ALTER TABLE "RM552164"."CT_DISPOSITIVOS_USUARIO" MODIFY ("ID_USUARIO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CT_GENERO
--------------------------------------------------------

  ALTER TABLE "RM552164"."CT_GENERO" MODIFY ("ID_GENERO" NOT NULL ENABLE);
  ALTER TABLE "RM552164"."CT_GENERO" MODIFY ("DS_GENERO" NOT NULL ENABLE);
  ALTER TABLE "RM552164"."CT_GENERO" MODIFY ("NM_GENERO" NOT NULL ENABLE);
  ALTER TABLE "RM552164"."CT_GENERO" ADD PRIMARY KEY ("ID_GENERO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS"  ENABLE;
  ALTER TABLE "RM552164"."CT_GENERO" MODIFY ("DS_LABEL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CT_ROLE
--------------------------------------------------------

  ALTER TABLE "RM552164"."CT_ROLE" MODIFY ("ID_ROLE" NOT NULL ENABLE);
  ALTER TABLE "RM552164"."CT_ROLE" MODIFY ("DS_LABEL" NOT NULL ENABLE);
  ALTER TABLE "RM552164"."CT_ROLE" MODIFY ("NM_ROLE" NOT NULL ENABLE);
  ALTER TABLE "RM552164"."CT_ROLE" ADD PRIMARY KEY ("ID_ROLE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS"  ENABLE;
  ALTER TABLE "RM552164"."CT_ROLE" ADD CONSTRAINT "UK4N8PE124X2TXCMU68N8AS7OAO" UNIQUE ("NM_ROLE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CT_ROLE_USUARIO
--------------------------------------------------------

  ALTER TABLE "RM552164"."CT_ROLE_USUARIO" MODIFY ("ID_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "RM552164"."CT_ROLE_USUARIO" MODIFY ("ID_ROLE" NOT NULL ENABLE);
  ALTER TABLE "RM552164"."CT_ROLE_USUARIO" ADD PRIMARY KEY ("ID_USUARIO", "ID_ROLE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CT_USUARIO
--------------------------------------------------------

  ALTER TABLE "RM552164"."CT_USUARIO" MODIFY ("ID_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "RM552164"."CT_USUARIO" MODIFY ("DT_NASCIMENTO" NOT NULL ENABLE);
  ALTER TABLE "RM552164"."CT_USUARIO" MODIFY ("DS_EMAIL" NOT NULL ENABLE);
  ALTER TABLE "RM552164"."CT_USUARIO" MODIFY ("NM_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "RM552164"."CT_USUARIO" MODIFY ("DS_SENHA" NOT NULL ENABLE);
  ALTER TABLE "RM552164"."CT_USUARIO" MODIFY ("ID_GENERO" NOT NULL ENABLE);
  ALTER TABLE "RM552164"."CT_USUARIO" ADD PRIMARY KEY ("ID_USUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CT_CONSUMO_ENERGETICO
--------------------------------------------------------

  ALTER TABLE "RM552164"."CT_CONSUMO_ENERGETICO" ADD CONSTRAINT "FKRC3JWJDVN75V6O1R2HKP60QG4" FOREIGN KEY ("ID_DISPOSITIVO")
	  REFERENCES "RM552164"."CT_DISPOSITIVO" ("ID_DISPOSITIVO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CT_DISPOSITIVO
--------------------------------------------------------

  ALTER TABLE "RM552164"."CT_DISPOSITIVO" ADD CONSTRAINT "FKA8ND6AG3GRIBF0R1BBBTSRV71" FOREIGN KEY ("ID_USUARIO")
	  REFERENCES "RM552164"."CT_USUARIO" ("ID_USUARIO") ENABLE;
  ALTER TABLE "RM552164"."CT_DISPOSITIVO" ADD CONSTRAINT "FKPOWX0NFWS3E7CBN2D1R7DFAV4" FOREIGN KEY ("ID_AMBIENTE")
	  REFERENCES "RM552164"."CT_AMBIENTE" ("ID_AMBIENTE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CT_DISPOSITIVOS_USUARIO
--------------------------------------------------------

  ALTER TABLE "RM552164"."CT_DISPOSITIVOS_USUARIO" ADD CONSTRAINT "FKGJ7H5LMSXYCKT5O1G9TWWL2V9" FOREIGN KEY ("ID_USUARIO")
	  REFERENCES "RM552164"."CT_USUARIO" ("ID_USUARIO") ENABLE;
  ALTER TABLE "RM552164"."CT_DISPOSITIVOS_USUARIO" ADD CONSTRAINT "FKHXGISKGMR8D2VJGVTAWVE3PAI" FOREIGN KEY ("ID_DISPOSITIVO")
	  REFERENCES "RM552164"."CT_DISPOSITIVO" ("ID_DISPOSITIVO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CT_ROLE_USUARIO
--------------------------------------------------------

  ALTER TABLE "RM552164"."CT_ROLE_USUARIO" ADD CONSTRAINT "FK48XPSRAPXJY7OHEG6LWKPJ7VH" FOREIGN KEY ("ID_USUARIO")
	  REFERENCES "RM552164"."CT_USUARIO" ("ID_USUARIO") ENABLE;
  ALTER TABLE "RM552164"."CT_ROLE_USUARIO" ADD CONSTRAINT "FKP0D3ONY8CV4CJY9ARO3N5INO7" FOREIGN KEY ("ID_ROLE")
	  REFERENCES "RM552164"."CT_ROLE" ("ID_ROLE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CT_USUARIO
--------------------------------------------------------

  ALTER TABLE "RM552164"."CT_USUARIO" ADD CONSTRAINT "FK3KJ17OWE2U415REBTY3APIIJ0" FOREIGN KEY ("ID_GENERO")
	  REFERENCES "RM552164"."CT_GENERO" ("ID_GENERO") ENABLE;
